### PR TITLE
Add a standard build workflow in key4hep

### PR DESCRIPTION
**Pull request by jmcarcell**
This PR is here to discuss the addition of a standard build workflow in key4hep, the changes in this PR are irrelevant.

I propose the addition of a standard build workflow that will be the same for all the repositories in key4hep. The action and workflow files are already in this repository and have the following features:

- Builds for AlmaLinux 9, CentOS 7 and Ubuntu 22.04, also for releases and nightlies, so right now it spawns a total of 6 jobs
- Most of the actual running happens in the action that would be here, meaning that it only would need to be changed in one place (for example changing to C++20)
- It uses images with cvmfs installed which should reduce the time it takes since loading cvmfs is quicker (and the github action only supports ubuntu). Some tests with k4FWCore can do some of the builds in 2-3 minutes but there are builds that take longer.
- Triggers on pushes (so people working on their own forks get it too) and it can also be triggered manually, for example for debugging.
- Removes the current package from the existing environment variables; this should make it work correctly in cases where it could still pick up something old.

The idea is that the current build workflows (only key4hep, not the LCG ones) would be replaced by this one in all the (CMake) repositories. The EDM4hep workflow does some testing of some downstream functionality, so that would have to be discussed.

This is how it will look at the bottom of PRs:

2023-12-14-183408_851x115_scrot

This is how it looks like in the github job tab (the six jobs on the right are initially grouped in one): 

2023-12-14-183346_1004x520_scrot

I think it's also a good place to discuss if we want to use the `-Werror` flag to convert warnings to errors since if left uncontrolled it's easy to add them.

### CODE REVIEW

**Comment by tmadlener** [comment]
I think this is a very good idea. I also like how the result looks in the end. How would we distribute this to the packages in the end? Similar to how we do it with other dotfiles (e.g. `.clang-format`), i.e. tracking them in one central repository and then just pushing them to the packages? Or would this be more like a github action that each package then simply uses instead of the the `run-lcg-view` action that we currently use?

**Comment by jmcarcell** [comment]
There is an [action](https://github.com/key4hep/key4hep-actions/blob/main/key4hep-build/action.yml) and a [workflow](https://github.com/key4hep/key4hep-actions/blob/main/workflows/key4hep-build.yaml) that uses the action ready to be pushed to the repos. The only thing the workflow does is spawn the six jobs and call the action. LCG workflows can also be added but not every package in key4hep is in LCG so they can't be added to all the repos (easily)

**Comment by tmadlener** [comment]
That makes sense. For me this looks good as it is. I would suggest to roll it out in parallel to the existing workflows just to have a direct comparison.

**Comment by jmcarcell** [comment]
The build workflow has been added so this PR doesn't serve its purpose anymore.

**Pull request closed without merging**
